services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_chat
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=chat_app
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: