[project]
name = "livechat"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "pytest-mock>=3.15.1",
    "ruff>=0.14.0",
]

[tool.mypy]
exclude = 'tests/'

[tool.coverage.run]
source = ["src"]
omit = ["**/__pycache__/*"]