from typing import Protocol
from uuid import UUID

from app.domain.entities.chat_room import ChatRoom


class ChatRoomRepository(Protocol):
    async def save(self, room: ChatRoom) -> ChatRoom: ...

    async def get(self, room_id: UUID) -> ChatRoom | None: ...

    async def search(self, query: str, limit: int = 20) -> list[ChatRoom]: ...

    async def update(self, room: ChatRoom) -> None: ...

    async def delete_by_id(self, room_id: UUID) -> None: ...

    async def list_by_user(self, user_id: UUID) -> list[ChatRoom]: ...

    async def list_top_room(self, limit: int, only_public: bool) -> list[ChatRoom]: ...

    async def add_participant(self, room_id: UUID, user_id: UUID) -> None: ...

    async def remove_participant(self, room_id: UUID, user_id: UUID) -> None: ...

    async def exists(self, name: str) -> bool: ...
