from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.entities.message import Message


class MessageRepository(Protocol):
    async def save(self, message: Message) -> None: ...

    async def get_recent_by_room(self, room_id: UUID, limit: int) -> list[Message]: ...

    async def get_by_id(self, message_id: UUID) -> Message | None: ...

    async def get_since(self, room_id: UUID, since: datetime) -> list[Message]: ...

    async def delete_by_id(self, message_id: UUID) -> None: ...

    async def count_by_room(self, room_id: UUID) -> int: ...

    async def list_by_user(self, user_id: UUID, limit: int = 50) -> list[Message]: ...
