from typing import Protocol
from uuid import UUID

from app.domain.entities.notification import Notification


class NotificationRepository(Protocol):
    async def save(self, notification: Notification) -> Notification: ...

    async def get_by_id(self, notification_id: UUID) -> Notification: ...

    async def get_user_notifications(
        self, user_id: UUID, unread_only: bool = False, limit: int = 10
    ) -> list[Notification]: ...

    async def mark_as_read(self, notification_id: UUID) -> None: ...

    async def delete_by_user_id(self, user_id: UUID) -> None: ...

    async def count_unread(self, user_id: UUID) -> int: ...

    async def mark_all_as_read(self, user_id: UUID) -> None: ...
