from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.entities.outbox import Outbox


class OutboxRepository(Protocol):
    async def save(self, outbox: Outbox) -> Outbox: ...

    async def get_by_id(self, outbox_id: UUID) -> Outbox: ...

    async def list_pending(self, limit: int = 100) -> list[Outbox]: ...

    async def mark_in_progress(self, outbox_id: UUID) -> bool: ...

    async def mark_sent(self, outbox_id: UUID, sent_at: datetime) -> None: ...

    async def mark_failed(self, outbox_id: UUID, error: str) -> None: ...

    async def delete_by_id(self, outbox_id: UUID) -> None: ...
