from typing import Protocol
from uuid import UUID

from app.domain.entities.room import Room


class RoomRepository(Protocol):
    async def save(self, room: Room) -> Room: ...

    async def get_by_id(self, room_id: UUID) -> Room | None: ...

    async def search(self, query: str, limit: int = 20) -> list[Room]: ...

    async def delete_by_id(self, room_id: UUID) -> None: ...

    async def list_top_room(self, limit: int, only_public: bool) -> list[Room]: ...

    async def add_participant(self, room_id: UUID) -> None: ...

    async def remove_participant(self, room_id: UUID) -> None: ...

    async def exists(self, name: str) -> bool: ...
