from typing import Protocol, Any


class CachePort(Protocol):
    async def get(self, key: str) -> Any | None: ...

    async def set(self, key: str, value: Any, ttl: int = 60) -> None: ...

    async def delete(self, key: str) -> None: ...

    async def exists(self, key: str) -> bool: ...

    async def incr(self, key: str, amount: int = 1) -> int: ...

    async def clear_prefix(self, prefix: str) -> None: ...
