from enum import Enum


class Environment(Enum):
    TEST = "TEST"
    DEV = "DEV"
    PROD = "PROD"


class AnalyticsEventType(Enum):
    MESSAGE_SENT = "MESSAGE_SENT"
    ROOM_CREATED = "ROOM_CREATED"
    ROOM_UPDATED = "ROOM_UPDATED"
    ROOM_DELETED = "ROOM_DELETED"
    USER_JOINED_ROOM = "USER_JOINED_ROOM"
    USER_LEFT_ROOM = "USER_LEFT_ROOM"
    JOIN_REQUEST_CREATED = "JOIN_REQUEST_CREATED"
    JOIN_REQUEST_ACCEPTED = "JOIN_REQUEST_ACCEPTED"
    JOIN_REQUEST_REJECTED = "JOIN_REQUEST_REJECTED"


class NotificationType(Enum):
    MESSAGE_SENT = "MESSAGE_RECEIVED"
    JOIN_REQUEST_CREATED = "JOIN_REQUEST_CREATED"
    JOIN_REQUEST_ACCEPTED = "JOIN_REQUEST_ACCEPTED"
    JOIN_REQUEST_REJECTED = "JOIN_REQUEST_REJECTED"
    MENTION = "MENTION"
    USER_JOINED = "USER_JOINED"
    USER_LEFT = "USER_LEFT"
    SYSTEM = "SYSTEM"


class RoomRole(Enum):
    OWNER = "OWNER"
    MEMBER = "MEMBER"


class JoinRequestStatus(Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class OutboxMessageType(Enum):
    JOIN_REQUEST_CREATED = "JOIN_REQUEST_CREATED"
    ROOM_CREATED = "ROOM_CREATED"
    NOTIFICATION = "NOTIFICATION"


class OutboxStatus(Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    SENT = "SENT"
    FAILED = "FAILED"
