from enum import Enum


class Environment(Enum):
    TEST = "TEST"
    DEV = "DEV"
    PROD = "PROD"


class AnalyticsEventType(Enum):
    MESSAGE_SENT = "MESSAGE_SENT"
    MESSAGE_EDITED = "MESSAGE_EDITED"
    MESSAGE_DELETED = "MESSAGE_DELETED"

    USER_REGISTERED = "USER_REGISTERED"
    USER_LOGGED_IN = "USER_LOGGED_IN"
    USER_LOGGED_OUT = "USER_LOGGED_OUT"
    USER_DELETED = "USER_DELETED"

    USER_CONNECTED = "USER_CONNECTED"
    USER_DISCONNECTED = "USER_DISCONNECTED"
    USER_FORCED_DISCONNECT = "USER_FORCED_DISCONNECT"

    ROOM_CREATED = "ROOM_CREATED"
    ROOM_UPDATED = "ROOM_UPDATED"
    ROOM_DELETED = "ROOM_DELETED"

    USER_JOINED_ROOM = "USER_JOINED_ROOM"
    USER_LEFT_ROOM = "USER_LEFT_ROOM"

    JOIN_REQUEST_CREATED = "JOIN_REQUEST_CREATED"
    JOIN_REQUEST_ACCEPTED = "JOIN_REQUEST_ACCEPTED"
    JOIN_REQUEST_REJECTED = "JOIN_REQUEST_REJECTED"

    NOTIFICATION_READ = "NOTIFICATION_READ"
    NOTIFICATIONS_ALL_READ = "NOTIFICATIONS_ALL_READ"


class NotificationType(Enum):
    JOIN_REQUEST_CREATED = "JOIN_REQUEST_CREATED"
    JOIN_REQUEST_ACCEPTED = "JOIN_REQUEST_ACCEPTED"
    JOIN_REQUEST_REJECTED = "JOIN_REQUEST_REJECTED"


class RoomRole(Enum):
    OWNER = "OWNER"
    MEMBER = "MEMBER"


class JoinRequestStatus(Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class OutboxMessageType(Enum):
    ANALYTICS = "ANALYTICS"
    NOTIFICATION = "NOTIFICATION"


class OutboxStatus(Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    SENT = "SENT"
    FAILED = "FAILED"


class BroadcastEventType(Enum):
    MESSAGE_CREATED = "MESSAGE_CREATED"
    MESSAGE_EDITED = "MESSAGE_EDITED"
    MESSAGE_DELETED = "MESSAGE_DELETED"
    USER_TYPING = "USER_TYPING"
    NOTIFICATION = "NOTIFICATION"
